# This is a basic workflow that is manually triggered

name: telegram-notify

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Update status
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: html
        message: |  #https://help.github.com/en/actions/reference/contexts-and-expression-syntax-for-github-actions#github-context
         🎉 Yay! <b>${{ github.actor }}</b> created a <b>${{ github.event_name }}</b> commit!
         
         <b>Commit message</b>: <i>${{ github.event.commits[0].message }}</i>
            
         See changes: <a href="https://github.com/${{ github.repository }}/commit/${{github.sha}}">click here</a>!
